services:
  database:
    image: imresamu/postgis:17-3.5.4-alpine3.23
    environment:
      POSTGRES_DB: agro
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agro -d agro"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
